### ISSUE TITLE
todo for production

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-cutter#2]
- [ ] add test for parser class of aiida-diff plugin
- [ ] move  manage.py to click
- [ ]  add instructions for running tests & examples to README
- [ ] add info to aiida-core docs (replaces plugin template)

**Comment by ltalirz** [comment]
production needs to begin nevertheless... replacing those with individual issues
